/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 22-Jun-2017 11:29:28 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "alumno_id_seq"
;

DROP SEQUENCE IF EXISTS "profesor_id_seq"
;

DROP SEQUENCE IF EXISTS "kardex_id_seq"
;

DROP SEQUENCE IF EXISTS "asistencia_id_seq"
;

DROP SEQUENCE IF EXISTS "grupo_id_seq"
;

DROP SEQUENCE IF EXISTS "boleta_inscripcion_id_seq"
;

DROP SEQUENCE IF EXISTS "curso_id_seq"
;

DROP SEQUENCE IF EXISTS "aula_id_seq"
;

/* Drop Tables */

DROP TABLE IF EXISTS "alumno" CASCADE
;

DROP TABLE IF EXISTS "profesor" CASCADE
;

DROP TABLE IF EXISTS "kardex" CASCADE
;

DROP TABLE IF EXISTS "asistencia" CASCADE
;

DROP TABLE IF EXISTS "grupo" CASCADE
;

DROP TABLE IF EXISTS "boleta_inscripcion" CASCADE
;

DROP TABLE IF EXISTS "boleta_grupo" CASCADE
;

DROP TABLE IF EXISTS "imparte" CASCADE
;

DROP TABLE IF EXISTS "curso" CASCADE
;

DROP TABLE IF EXISTS "prerequisitos" CASCADE
;

DROP TABLE IF EXISTS "horario" CASCADE
;

DROP TABLE IF EXISTS "aula" CASCADE
;

/* Create Tables */

CREATE TABLE "alumno"
(
	"id" integer NOT NULL DEFAULT nextval(('"alumno_id_seq"'::text)::regclass),
	"nombres" varchar(100)	 NOT NULL,
	"apellidos" varchar(100)	 NOT NULL,
	"telefono" integer NOT NULL,
	"fecha_nacimiento" date NOT NULL,
	"fecha_ingreso" date NOT NULL,
	"estado" boolean NOT NULL
)
;

CREATE TABLE "profesor"
(
	"id" integer NOT NULL DEFAULT nextval(('"profesor_id_seq"'::text)::regclass),
	"nombres" varchar(100)	 NOT NULL,
	"apellidos" varchar(100)	 NOT NULL,
	"telefono" integer NOT NULL,
	"fecha_postulacion" date NOT NULL,
	"estado" boolean NOT NULL
)
;

CREATE TABLE "kardex"
(
	"id" integer NOT NULL DEFAULT nextval(('"kardex_id_seq"'::text)::regclass),
	"nota" varchar(2)	 NULL,
	"mes" integer NOT NULL,
	"gestion" integer NOT NULL,
	"id_alumno" integer NULL,
	"id_grupo" integer NULL
)
;

CREATE TABLE "asistencia"
(
	"id" integer NOT NULL DEFAULT nextval(('"asistencia_id_seq"'::text)::regclass),
	"estado" varchar(1)	 NOT NULL,
	"fecha" date NOT NULL,
	"id_kardex" integer NULL
)
;

CREATE TABLE "grupo"
(
	"id" integer NOT NULL DEFAULT nextval(('"grupo_id_seq"'::text)::regclass),
	"nombre" varchar(100)	 NOT NULL,
	"id_curso" integer NULL
)
;

CREATE TABLE "boleta_inscripcion"
(
	"id" integer NOT NULL DEFAULT nextval(('"boleta_inscripcion_id_seq"'::text)::regclass),
	"fecha_inscripcion" date NOT NULL,
	"id_alumno" integer NULL
)
;

CREATE TABLE "boleta_grupo"
(
	"id_boleta" integer NOT NULL,
	"id_grupo" integer NOT NULL
)
;

CREATE TABLE "imparte"
(
	"id_profesor" integer NOT NULL,
	"id_grupo" integer NOT NULL,
	"fecha_asignacion" date NOT NULL
)
;

CREATE TABLE "curso"
(
	"id" integer NOT NULL DEFAULT nextval(('"curso_id_seq"'::text)::regclass),
	"nombre" varchar(100)	 NOT NULL,
	"descripcion" varchar(100)	 NOT NULL,
	"estado" boolean NOT NULL
)
;

CREATE TABLE "prerequisitos"
(
	"id_curso" integer NOT NULL,
	"id_prerequisito" integer NOT NULL
)
;

CREATE TABLE "horario"
(
	"id_grupo" integer NOT NULL,
	"id" integer NOT NULL,
	"dia" varchar(50)	 NOT NULL,
	"hora_inicio" varchar(5)	 NOT NULL,
	"hora_fin" varchar(5)	 NOT NULL,
	"id_aula" integer NULL
)
;

CREATE TABLE "aula"
(
	"id" integer NOT NULL DEFAULT nextval(('"aula_id_seq"'::text)::regclass),
	"nombre" varchar(100)	 NULL,
	"capacidad" integer NULL
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE "alumno_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "profesor_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "kardex_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "asistencia_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "grupo_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "boleta_inscripcion_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "curso_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "aula_id_seq" INCREMENT 1 START 1
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "alumno" ADD CONSTRAINT "PK_alumno"
	PRIMARY KEY ("id")
;

ALTER TABLE "profesor" ADD CONSTRAINT "PK_profesor"
	PRIMARY KEY ("id")
;

ALTER TABLE "kardex" ADD CONSTRAINT "PK_kardex"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_kardex_alumno" ON "kardex" ("id_alumno" ASC)
;

CREATE INDEX "IXFK_kardex_grupo" ON "kardex" ("id_grupo" ASC)
;

ALTER TABLE "asistencia" ADD CONSTRAINT "PK_asistencia"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_asistencia_kardex" ON "asistencia" ("id_kardex" ASC)
;

ALTER TABLE "grupo" ADD CONSTRAINT "PK_grupo"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_grupo_curso" ON "grupo" ("id_curso" ASC)
;

ALTER TABLE "boleta_inscripcion" ADD CONSTRAINT "PK_boleta_inscripcion"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_boleta_inscripcion_alumno" ON "boleta_inscripcion" ("id_alumno" ASC)
;

ALTER TABLE "boleta_grupo" ADD CONSTRAINT "PK_boleta_grupo"
	PRIMARY KEY ("id_boleta","id_grupo")
;

CREATE INDEX "IXFK_boleta_grupo_boleta_inscripcion" ON "boleta_grupo" ("id_boleta" ASC)
;

CREATE INDEX "IXFK_boleta_grupo_grupo" ON "boleta_grupo" ("id_grupo" ASC)
;

ALTER TABLE "imparte" ADD CONSTRAINT "PK_imparte"
	PRIMARY KEY ("id_profesor","id_grupo")
;

CREATE INDEX "IXFK_imparte_grupo" ON "imparte" ("id_grupo" ASC)
;

CREATE INDEX "IXFK_imparte_profesor" ON "imparte" ("id_profesor" ASC)
;

ALTER TABLE "curso" ADD CONSTRAINT "PK_curso"
	PRIMARY KEY ("id")
;

ALTER TABLE "prerequisitos" ADD CONSTRAINT "PK_prerequisitos"
	PRIMARY KEY ("id_curso","id_prerequisito")
;

CREATE INDEX "IXFK_prerequisitos_curso" ON "prerequisitos" ("id_curso" ASC)
;

CREATE INDEX "IXFK_prerequisitos_curso_02" ON "prerequisitos" ("id_prerequisito" ASC)
;

ALTER TABLE "horario" ADD CONSTRAINT "PK_horario"
	PRIMARY KEY ("id_grupo","id")
;

CREATE INDEX "IXFK_horario_aula" ON "horario" ("id_aula" ASC)
;

CREATE INDEX "IXFK_horario_grupo" ON "horario" ("id_grupo" ASC)
;

ALTER TABLE "aula" ADD CONSTRAINT "PK_aula"
	PRIMARY KEY ("id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "kardex" ADD CONSTRAINT "FK_kardex_alumno"
	FOREIGN KEY ("id_alumno") REFERENCES "alumno" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "kardex" ADD CONSTRAINT "FK_kardex_grupo"
	FOREIGN KEY ("id_grupo") REFERENCES "grupo" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "asistencia" ADD CONSTRAINT "FK_asistencia_kardex"
	FOREIGN KEY ("id_kardex") REFERENCES "kardex" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "grupo" ADD CONSTRAINT "FK_grupo_curso"
	FOREIGN KEY ("id_curso") REFERENCES "curso" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "boleta_inscripcion" ADD CONSTRAINT "FK_boleta_inscripcion_alumno"
	FOREIGN KEY ("id_alumno") REFERENCES "alumno" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "boleta_grupo" ADD CONSTRAINT "FK_boleta_grupo_boleta_inscripcion"
	FOREIGN KEY ("id_boleta") REFERENCES "boleta_inscripcion" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "boleta_grupo" ADD CONSTRAINT "FK_boleta_grupo_grupo"
	FOREIGN KEY ("id_grupo") REFERENCES "grupo" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "imparte" ADD CONSTRAINT "FK_imparte_grupo"
	FOREIGN KEY ("id_grupo") REFERENCES "grupo" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "imparte" ADD CONSTRAINT "FK_imparte_profesor"
	FOREIGN KEY ("id_profesor") REFERENCES "profesor" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "prerequisitos" ADD CONSTRAINT "FK_prerequisitos_curso"
	FOREIGN KEY ("id_curso") REFERENCES "curso" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "prerequisitos" ADD CONSTRAINT "FK_prerequisitos_curso_02"
	FOREIGN KEY ("id_prerequisito") REFERENCES "curso" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "horario" ADD CONSTRAINT "FK_horario_aula"
	FOREIGN KEY ("id_aula") REFERENCES "aula" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "horario" ADD CONSTRAINT "FK_horario_grupo"
	FOREIGN KEY ("id_grupo") REFERENCES "grupo" ("id") ON DELETE Cascade ON UPDATE Cascade
;
